baseURL = 'https://math.physicsderived.club'
languageCode = 'en-us'
title = 'Math Derived'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
      [markup.goldmark.renderer]
        unsafe = true
        
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

[params]
  math = true